# Assumes that conda, pip and build-essentials are installed
---
name: gpuocean_opendrift
channels:
- conda-forge
- opendrift

dependencies:
- python=3.7
- conda-build
- numpy
- matplotlib=3.3.3
- jupyter
- netcdf4
- pytest
- xmlrunner
- scipy
- pandas
- pytables
- nb_conda_kernels
- nbdime
- mpi4py
- openssl
- requests
- pip
- pyproj
- pytools
- cartopy
- ffmpeg
- opendrift
# Activate environment and install the following packages using pip:
# $ conda activate gpuocean_parcels_opendrift
#  - pycuda: $ pip3 install --no-deps -U pycuda
# on Windows: make sure your visual studio c++ compiler is available in PATH
# PATH should have something like C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\
